#!/usr/bin/env bash
# Radio Net server setup: LiveKit + Radio Net API + Caddy (auto-HTTPS) on one Ubuntu 24.04 VPS.
# Run as root ON THE VPS from the uploaded source dir (deploy.sh does this for you):
#   sudo bash /opt/radionet-src/deploy/setup.sh
# Idempotent: safe to re-run after code changes. Secrets are generated once and kept in /etc/radionet.
#
# Optional env overrides:
#   PUBLIC_IP=1.2.3.4        skip auto-detection
#   API_HOST=radio.example.nz  LK_HOST=lk.example.nz   (when you own a domain; default *.sslip.io)
#   ACME_EMAIL=you@example.com  (Let's Encrypt expiry notices; also enables ZeroSSL fallback)
#   RENDER_ONLY=/tmp/out     write config files there and exit (used for local testing)
set -euo pipefail

LIVEKIT_VERSION="${LIVEKIT_VERSION:-1.13.9}"
CADDY_VERSION="${CADDY_VERSION:-2.11.7}"
NODE_VERSION="${NODE_VERSION:-24.21.0}"

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # contains deploy/ and server/
APP_DIR=/opt/radionet
ETC_DIR=/etc/radionet
RENDER_ONLY="${RENDER_ONLY:-}"

log() { printf '\n== %s\n' "$*"; }

# ---------- public IP + hostnames ----------
detect_ip() {
  local ip
  ip="$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)"
  if [[ ! "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    ip="$(ip -4 route get 1.1.1.1 | awk '{for(i=1;i<NF;i++) if($i=="src"){print $(i+1); exit}}')"
  fi
  printf '%s' "$ip"
}
PUBLIC_IP="${PUBLIC_IP:-$(detect_ip)}"
[[ "$PUBLIC_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Could not detect public IPv4; set PUBLIC_IP=" >&2; exit 1; }
DASHED="${PUBLIC_IP//./-}"
API_HOST="${API_HOST:-radio-${DASHED}.sslip.io}"
LK_HOST="${LK_HOST:-lk-${DASHED}.sslip.io}"

# ---------- secrets (generated once) ----------
rand() { head -c "$1" /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "$2"; }
SECRETS_FILE="${RENDER_ONLY:+$RENDER_ONLY/secrets.env}"
SECRETS_FILE="${SECRETS_FILE:-$ETC_DIR/secrets.env}"
mkdir -p "$(dirname "$SECRETS_FILE")"
if [[ ! -s "$SECRETS_FILE" ]]; then
  umask 077
  cat > "$SECRETS_FILE" <<SECRETS
LIVEKIT_API_KEY=API$(rand 32 12)
LIVEKIT_API_SECRET=$(rand 96 48)
COMMUNITY_SETUP_CODE=$(rand 32 4)-$(rand 32 4)-$(rand 32 4)
SECRETS
  umask 022
fi
# shellcheck disable=SC1090
source "$SECRETS_FILE"

# ---------- config files ----------
render_configs() {
  local out="$1"
  mkdir -p "$out"
  cat > "$out/livekit.yaml" <<YAML
# LiveKit server config (generated by setup.sh). Signal (7880) is only reachable through Caddy on 443.
port: 7880
bind_addresses:
  - 127.0.0.1
rtc:
  tcp_port: 7881          # ICE/TCP fallback for networks that block UDP
  udp_port: 7882          # all media multiplexed on one UDP port (simple firewall)
  use_external_ip: true
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
room:
  empty_timeout: 300
  max_participants: 50
logging:
  level: info
YAML

  cat > "$out/Caddyfile" <<CADDY
# Caddy reverse proxy with automatic HTTPS (generated by setup.sh).
{
${ACME_EMAIL:+	email ${ACME_EMAIL}}
}

${API_HOST} {
	encode gzip

	# Browser UI preview: static, fully mocked build (no API or LiveKit calls; CSP blocks any fetch/WebSocket).
	redir /preview /preview/ 308
	handle_path /preview/* {
		root * ${APP_DIR}/preview
		header Content-Security-Policy "default-src 'self'; connect-src 'none'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'"
		header X-Robots-Tag "noindex"
		file_server
	}

	handle {
		reverse_proxy 127.0.0.1:8787
	}
}

${LK_HOST} {
	reverse_proxy 127.0.0.1:7880
}
CADDY

  cat > "$out/api.env" <<ENV
# Radio Net API environment (generated by setup.sh)
NODE_ENV=production
HOST=127.0.0.1
PORT=8787
SEED_DEV=0
TRUST_PROXY=1
JOIN_RATE_LIMIT=30
LIVEKIT_URL=wss://${LK_HOST}
LIVEKIT_HTTP_URL=http://127.0.0.1:7880
RN_DATA_FILE=/var/lib/radionet/store.json
ENV
}

if [[ -n "$RENDER_ONLY" ]]; then
  render_configs "$RENDER_ONLY"
  echo "Rendered to $RENDER_ONLY (API_HOST=$API_HOST LK_HOST=$LK_HOST)"
  exit 0
fi

[[ $EUID -eq 0 ]] || { echo "Run as root (sudo)." >&2; exit 1; }
[[ -d "$SRC_DIR/server/src" ]] || { echo "Expected server source at $SRC_DIR/server" >&2; exit 1; }

log "Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates ufw rsync xz-utils unattended-upgrades >/dev/null

log "User and directories"
id radionet >/dev/null 2>&1 || useradd --system --home "$APP_DIR" --shell /usr/sbin/nologin radionet
mkdir -p "$APP_DIR/bin" "$APP_DIR/server" "$ETC_DIR" /var/lib/caddy /var/lib/radionet
chown radionet:radionet /var/lib/radionet
chmod 750 /var/lib/radionet
chmod 750 "$ETC_DIR"; chgrp radionet "$ETC_DIR"; chmod 640 "$SECRETS_FILE"; chgrp radionet "$SECRETS_FILE"

log "Node.js v$NODE_VERSION"
if [[ "$("$APP_DIR/node/bin/node" -v 2>/dev/null || true)" != "v$NODE_VERSION" ]]; then
  rm -rf "$APP_DIR/node" && mkdir -p "$APP_DIR/node"
  curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" | tar xJ -C "$APP_DIR/node" --strip-components=1
fi

log "LiveKit v$LIVEKIT_VERSION"
if ! "$APP_DIR/bin/livekit-server" --version 2>/dev/null | grep -q "$LIVEKIT_VERSION"; then
  curl -fsSL "https://github.com/livekit/livekit/releases/download/v${LIVEKIT_VERSION}/livekit_${LIVEKIT_VERSION}_linux_amd64.tar.gz" | tar xz -C "$APP_DIR/bin" livekit-server
fi

log "Caddy v$CADDY_VERSION"
if ! "$APP_DIR/bin/caddy" version 2>/dev/null | grep -q "v$CADDY_VERSION"; then
  curl -fsSL "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz" | tar xz -C "$APP_DIR/bin" caddy
fi
setcap 'cap_net_bind_service=+ep' "$APP_DIR/bin/caddy"

log "Radio Net API"
rsync -a --delete --exclude node_modules --exclude '*.log' "$SRC_DIR/server/" "$APP_DIR/server/"
(cd "$APP_DIR/server" && PATH="$APP_DIR/node/bin:$PATH" npm ci --no-audit --no-fund --loglevel=error)

log "Browser UI preview (optional)"
if [[ -f "$SRC_DIR/preview/index.html" ]]; then
  mkdir -p "$APP_DIR/preview"
  rsync -a --delete "$SRC_DIR/preview/" "$APP_DIR/preview/"
  echo "Preview installed: https://${API_HOST}/preview/"
else
  echo "No preview build in $SRC_DIR/preview; /preview/ will 404 (run pack.sh with PREVIEW_DIST set)."
fi
chown -R radionet:radionet "$APP_DIR" /var/lib/caddy

log "Configs"
render_configs "$ETC_DIR"
chgrp radionet "$ETC_DIR"/*; chmod 640 "$ETC_DIR"/*

log "systemd units"
install -m 644 "$SRC_DIR/deploy/systemd/"*.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now livekit.service radionet-api.service radionet-caddy.service
systemctl restart livekit.service radionet-api.service radionet-caddy.service

log "Firewall"
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow 22/tcp   comment 'ssh' >/dev/null
ufw allow 80/tcp   comment 'http (ACME + redirect)' >/dev/null
ufw allow 443/tcp  comment 'https: API + LiveKit signalling' >/dev/null
ufw allow 7881/tcp comment 'LiveKit ICE/TCP' >/dev/null
ufw allow 7882/udp comment 'LiveKit media (UDP mux)' >/dev/null
ufw --force enable >/dev/null

log "Health checks"
ok=1
for _ in $(seq 1 30); do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
curl -fsS http://127.0.0.1:8787/health >/dev/null || { echo "API not healthy: journalctl -u radionet-api"; ok=0; }
curl -fsS http://127.0.0.1:7880/ >/dev/null || { echo "LiveKit not healthy: journalctl -u livekit"; ok=0; }
for _ in $(seq 1 60); do curl -fsS "https://${API_HOST}/health" >/dev/null 2>&1 && break; sleep 2; done
curl -fsS "https://${API_HOST}/health" >/dev/null || { echo "HTTPS not ready yet (cert issuance?): journalctl -u radionet-caddy"; ok=0; }

cat <<DONE

==========================================================
 Radio Net server $( ((ok)) && echo READY || echo 'needs attention (see above)')
 API (put in the client as VITE_API_URL): https://${API_HOST}
 LiveKit (handed to clients by the API):  wss://${LK_HOST}
 UI preview (mocked, if packed):           https://${API_HOST}/preview/
 Community setup code (keep private):     ${COMMUNITY_SETUP_CODE:0:4}-****-**** (full value in ${SECRETS_FILE})
 Secrets: ${SECRETS_FILE}
 Logs:    journalctl -u livekit -u radionet-api -u radionet-caddy -f
==========================================================
DONE
